aruco_pick_place_node:
  ros__parameters:
    image_topic: /astra/rgb/image_raw
    camera_info_topic: /astra/rgb/camera_info

    dictionary: DICT_4X4_50
    marker_size: 0.04

    use_tf: true
    base_frame: world
    camera_tf_frame: astra_link_optical
    tf_timeout_sec: 0.05

    aruco_yaw_edge: top
    yaw_step_px: 60.0
    yaw_offset_deg: 0.0

    use_detected_z: true
    pick_z: 0.25
    pick_z_offset: 0.0

    place_x: 0.30
    place_y: 0.00
    place_z: 0.045

    gripper_down_quat_xyzw: [0.7071, 0.7071, 0.0, 0.0]
    use_yaw_for_grasp: true
    use_yaw_for_place: false

    gripper: 0.01
    velocity_scale: 0.3

    action_name: /pickplace
    auto_send: true
    send_once: true
    min_goal_interval_sec: 2.0

    stable_samples: 1
    max_sample_std_m: 1.0

    target_marker_id: -1

    enable_safety_check: true
    x_min: 0.10
    x_max: 0.65
    y_min: -0.35
    y_max: 0.35

    draw_debug: true
    draw_axes: false
    print_every_detection: true