<?xml version="1.0"?>
<package format="3">
  <name>task_planner</name>
  <version>0.0.3</version>
  <description>Simple MoveIt test package matched to panda_moveit.</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_visual_tools</depend>

  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>panda_moveit</exec_depend>
  <exec_depend>panda_description</exec_depend>
  <exec_depend>panda_controller</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
