aruco_detect_node:
  ros__parameters:
    #image_topic: "/astra/rgb/image_raw"
    #camera_info_topic: "/astra/rgb/camera_info"

    image_topic: "/webcam/image_raw"
    camera_info_topic: "/webcam/camera_info"

    camera_frame: "astra_link_optical"

    dictionary: "DICT_4X4_50"
    marker_size: 0.03

    enable_pose: false
    draw_debug: true
