pixel_to_base_mapper_node:
  ros__parameters:
    output_frame_id: "camera_color_optical_frame"

    camera_info_topic: "/camera/camera/color/camera_info"
    color_image_topic: "/camera/camera/color/image_raw"
    depth_image_topic: "/camera/camera/aligned_depth_to_color/image_raw"

    wood_detection_topic: "/vision/wood_detection"
    box_detection_topic: "/vision/box_detection"

    wood_objects_topic: "/vision/wood_objects"
    box_objects_topic: "/vision/box_objects"

    default_box_size_x_m: 0.08
    default_box_size_y_m: 0.08
    default_box_size_z_m: 0.05
    box_obstacle_margin_m: 0.02

    fake_depth_m: 0.55
    use_fake_depth_if_missing: false

    overlay_timeout_sec: 1.0
    stale_timeout_sec: 2.0

    enable_yaw_estimation: true
    yaw_class_name: "wood"
    mask_shrink: 0.92
    morph_kernel_size: 5
    min_hsv_area_ratio: 0.80

    h_min: 5
    h_max: 35
    s_min: 40
    s_max: 255
    v_min: 40
    v_max: 255

    enable_yaw_smoothing: true
    yaw_avg_frames: 5
    show_debug_text: false
    yaw_arrow_length_px: 50
    default_grasp_yaw_deg: 0.0
    verbose_yaw_log: true
