yolo_detect_node:
  ros__parameters:

    #image_topic: "/camera/color/image_raw"
    image_topic: "/astra/rgb/image_raw"

    annotated_image_topic: "/vision/yolo/image_annotated"

    detections_topic: "/vision/yolo/detections_json"

    model_path: "/home/minhquang/ros2/src/robot_vision_pipeline/models/best.pt"
    #model_path: "yolov8n.pt"

    # CPU: "cpu"
    # GPU: "0"
    device: "cpu"

    conf_threshold: 0.35
    iou_threshold: 0.45
    imgsz: 256

    show_gui: false

    class_filter: "wood"

    verbose_log: false