yolo_detect_node:
  ros__parameters:
    image_topic: "/camera/camera/color/image_raw"
    camera_info_topic: "/camera/camera/color/camera_info"
    annotated_image_topic: "/vision/yolo/image_annotated"
    detections_topic: "/vision/yolo/detections_json"
    model_path: "models/yolov8.pt"
    device: "cpu"
    conf_threshold: 0.35
    iou_threshold: 0.45
    imgsz: 256
    max_det: 20
    detect_period_sec: 0.0
    show_gui: false
    publish_annotated: true
    image_qos: "reliable"
    class_filter: "wood,box"
    verbose_log: false
    enable_roi_crop: true
    roi_x: 125
    roi_y: 150
    roi_width: 360
    roi_height: 300
    publish_roi_debug_image: true

pixel_to_base_mapper_node:
  ros__parameters:
    draw_yolo_roi: true
    roi_x: 125
    roi_y: 150
    roi_width: 360
    roi_height: 260
