<?xml version="1.0"?>
<package format="3">
  <name>robot_gui</name>
  <version>0.1.0</version>
  <description>Qt based GUI for the 6DOF robot using the Designer .ui layout.</description>
  <maintainer email="tranminhquang617@gmail.com">Minh Quang Tran</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>robot_hardware_interface</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-pyqt5</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>robot_description</exec_depend>
  <exec_depend>robot_moveit</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
