rs485_hw:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    serial_timeout_s: 0.2
    poll_status_hz: 4.0
    pos_timeout_s: 0.35
    status_timeout_s: 0.5
    all_token: 153
    joint_names: ["joint_1","joint_2","joint_3","joint_4","joint_5","joint_6","joint_gl","joint_gl"] 
    # Axis IDs on STM32 firmware are usually 1-based (1..N). Change if your firmware is 0-based.
    axis_ids: [0,1,2,3,4,5,6,7]

    proto_header1: 187   # 0xBB (default). 
    proto_tail1:   255   # 0xFF (default). 
    proto_stuff:   170   # 0xAA
