robot_hw:
  ros__parameters:
    robot_ip: "192.168.2.50"
    robot_port: 5000
    connect_timeout_ms: 2000
    read_timeout_ms: 50
    poll_pos_hz: 20.0
    all_token: 153
    joint_names: ["joint_1","joint_2","joint_3","joint_4","joint_5","joint_6"]
    # Axis IDs are 0-based: 0->joint_1, 1->joint_2, ..., 5->joint_6.
    axis_ids: [0,1,2,3,4,5]
